[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:create_app()"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 